# 1. EL IDIOMA DE CERVANTES (Para recuperar la Ñ y la distribución española)
input {
    kb_layout = es
}

# 2. PURGAR LOS CONTROLES DEL CREADOR (Desbindear)
unbind = SUPER, T
unbind = SUPER, W

# 3. TUS ATAJOS DE PC MASTER RACE
bind = SUPER, Return, exec, kitty
bind = SUPER, B, exec, zen-browser

# 4. EL CHEAT CODE DE LOS ESCRITORIOS (Mover apps con Super + Shift + Número)
bind = SUPER+Shift, 1, movetoworkspace, 1
bind = SUPER+Shift, 2, movetoworkspace, 2
bind = SUPER+Shift, 3, movetoworkspace, 3
bind = SUPER+Shift, 4, movetoworkspace, 4
bind = SUPER+Shift, 5, movetoworkspace, 5
bind = SUPER+Shift, 6, movetoworkspace, 6
bind = SUPER+Shift, 7, movetoworkspace, 7
bind = SUPER+Shift, 8, movetoworkspace, 8
bind = SUPER+Shift, 9, movetoworkspace, 9
bind = SUPER+Shift, 0, movetoworkspace, 10

exec-once = killall swww || killall hyprpaper; linux-wallpaperengine --assets-dir ~/.local/share/Steam/steamapps/common/wallpaper_engine --screen-root DP-3 827148653 &
exec-once = gnome-keyring-daemon --start --components=secrets

bind = SUPER SHIFT, Return, exec, spotify-launcher & discord & steam
